ProjectC/CaveroApp/Pages/Aanwezig_button.cshtml.cs
using System.Drawing;
using System.Security.Claims;
using CaveroApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;

namespace CaveroApp.Pages;

public class Aanwezig_button : PageModel
{
    private CaveroAppContext Context { get; }
    public Aanwezig_button(CaveroAppContext context)
    {
        Context = context;
    }

    public bool AvailableToday()
    {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var AreAtWork = (from a in Context.Attendances 
            join u in Context.Users on a.user_id equals u.Id
            where DateTime.UtcNow.Date.Equals(a.date.Date)  select u.Id).ToList();
        return AreAtWork.Contains(userId);
    }
    public IActionResult OnPostSetUnavailable()
    {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userId != null) 
        {
            List<CaveroAppContext.Attendance> currentUser = (from a in Context.Attendances 
                where a.user_id == userId && a.date == DateTime.UtcNow.Date select a).ToList();
            foreach (CaveroAppContext.Attendance attendance in currentUser)
            {
                Context.Attendances.Remove(attendance);
            }
            Context.SaveChanges();
            Console.WriteLine("afwezig gezet");
        }

        return RedirectToPage();
    }

    public IActionResult OnPostSetAvailable()
    {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userId != null) 
        {   
            CaveroAppContext.Attendance newAttendance = new CaveroAppContext.Attendance()
                { user_id = userId, date = DateTime.UtcNow.Date };
            Context.Attendances.Add(newAttendance);
            Context.SaveChanges();
            Console.WriteLine("aanwezig gezet");
        }

        return RedirectToPage();
    }

    public void OnGet()
    {
        
    }
}

ProjectC/CaveroApp/Pages/Attendance.cshtml.cs
using System.Security.Claims;
using CaveroApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static CaveroApp.Services.CustomClasses;

namespace CaveroApp.Pages;

[Authorize]
public class Attendance : PageModel
{
    // Database context
    public CaveroAppContext Context { get; }
    
    // Monday - Friday
    // First item is monday, last item is friday in dates.
    public (DateTime, DateTime) Week { get; set; }
    
    // The day that the user has chosen to view events for
    public static DateTime ChosenDay { get; set; }
    
    // constructor
    public Attendance(CaveroAppContext context)
    {
        Context = context;
    }
    
    /// <summary>
    /// This function gets all the attendances for the current week, based on the dates listed in the Week Tuple.
    /// It returns a list of WeekInfo objects, which contain the date and all the attendances for that date.
    /// </summary>
    public List<WeekAttendances> GetWeekAttendances()
    {
        var week = new List<WeekAttendances>();
        var StartDay = Week.Item1;
        int count = 0;
        while (StartDay <= Week.Item2)
        {
            var events = new WeekAttendances
            {
                Date = StartDay,
                allUsers = (from x in Context.Attendances 
                    join u in Context.Users on x.user_id equals u.Id
                    where x.date.Date.Equals(StartDay.Date.Date) select u).ToList()
            };
            week.Add(events);
            count++;
            StartDay = StartDay.AddDays(1);
        }
        return week;
    }

    public bool IsAttending(string userID, DateTime date)
    {
        return Context.Attendances.Any(x => x.user_id == userID && x.date.Date == date.Date);
    }
    
    public void OnGet()
    {
        // This variable is used to set the event date to the current date, so the user starts at the current week instead of a random date.
        // This is set to true to signify that it shouldn't happen again unless the page is completely refreshed,
        // so the user doesn't keep going back to the initial start date when trying to switch the week view.
        bool actionAlreadyPerformed = bool.TryParse(HttpContext.Session.GetString("AttendanceInitialSet"), out var result);

        if (!actionAlreadyPerformed)
        {
            ChosenDay = DateTime.UtcNow;
            // Set the session variable to indicate that the action has been performed
            HttpContext.Session.SetString("AttendanceInitialSet", true.ToString());
        }
        Week = Services.DateServices.GetCurrentWeek(ChosenDay);
    }
    
    /// <summary>
    ///     This function is called when the user clicks the "Next Week" button.
    ///     It adds 7 Days to the ChosenDay variable, which means the next Get() call will get the events for that week.
    /// </summary>
    /// <returns>
    ///     A RedirectToPageResult, which redirects to the same page,
    ///     without keeping a post form blocking the user from refreshing the page.
    /// </returns>
    public IActionResult OnPostWeekForward()
    {
        ChosenDay = ChosenDay.AddDays(7);
        return RedirectToPage();
    }

    /// <summary>
    ///     This function is called when the user clicks the "Last Week" button.
    ///     It adds -7 Days to the ChosenDay variable, which means the next Get() call will get the events for that week.
    /// </summary>
    /// <returns>
    ///     A RedirectToPageResult, which redirects to the same page,
    ///     without keeping a post form blocking the user from refreshing the page.
    /// </returns>
    public IActionResult OnPostWeekBackward()
    {
        ChosenDay = ChosenDay.AddDays(-7);
        return RedirectToPage();
    }

    /// <summary>
    /// This method is triggered when a user decides to join an event.
    /// </summary>
    /// <param name="userID">The ID of the user who wants to join the event.</param>
    /// <param name="date">The date of the event the user wants to join, in the format "dd-mm-yyyy".</param>
    /// <returns>A RedirectToPageResult, which redirects to the same page, without keeping a post form blocking the user from refreshing the page.</returns>
    public IActionResult OnPostUserJoin(string userID, string date)
    {
        var splitDate = date.Split("-").Select(x => Convert.ToInt32(x)).ToArray();
        var newDate = DateTime.SpecifyKind(new DateTime(splitDate[2], splitDate[1], splitDate[0]), DateTimeKind.Utc);
        if (newDate.Date >= DateTime.UtcNow.Date)
        {
                        Context.Attendances.Add(new CaveroAppContext.Attendance()
                        {
                            user_id = userID,
                            date = newDate,
                        });
                        Context.SaveChanges();
        }
        return RedirectToPage();
    }
    
    /// <summary>
    /// This method is triggered when a user decides to leave an event.
    /// </summary>
    /// <param name="userID">The ID of the user who wants to leave the event.</param>
    /// <param name="date">The date of the event the user wants to leave, in the format "dd-mm-yyyy".</param>
    /// <returns>A RedirectToPageResult, which redirects to the same page, without keeping a post form blocking the user from refreshing the page.</returns>
    public IActionResult OnPostUserLeave(string userID, string date)
    {
        var splitDate = date.Split("-").Select(x => Convert.ToInt32(x)).ToArray();
        var newDate = DateTime.SpecifyKind(new DateTime(splitDate[2], splitDate[1], splitDate[0]), DateTimeKind.Utc);
        if (newDate.Date >= DateTime.UtcNow.Date)
        {
             var Att = Context.Attendances.First(x => x.user_id == userID && x.date.Date == newDate.Date);
             Context.Remove(Att);
             Context.SaveChanges();
        }
 
        return RedirectToPage();
    }
    
    
}

ProjectC/CaveroApp/Pages/Dashboard.cshtml.cs
using System.Data.Entity;
using System.Globalization;
using System.Security.Claims;
using CaveroApp.Areas.Identity.Data;
using CaveroApp.Data;
using CaveroApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CaveroApp.Pages;

[Authorize]
public class Dashboard : PageModel
{
    private CaveroAppContext Context { get; }
    
    // Monday - Friday
    // First item is monday, last item is friday in dates.
    public (DateTime, DateTime) Week { get; set; }
    public int EmployeeCount { get; set; }
    public int EventCount { get; set; }
    
    [BindProperty]
    public CheckInModel CheckModel { get; set; }

    // use dependency injection to get the database context
    public Dashboard(CaveroAppContext context)
    {
        Context = context;
    }

    public class CheckInModel
    {
        public string Date { get; set; }
    }
    //<summary>
    //    This function grabs stats from the database, namely how many users are present today,
    //    and how many events are taking place this week.
    //    It populates the fields EmployeeCount and EventCount with the results.
    //</summary>
    public void GetTodayStats()
    {
        var emp_count = (from a in Context.Attendances
            join u in Context.Users on a.user_id equals u.Id
            where DateTime.UtcNow.Date.Equals(a.date.Date) select u).ToList().Distinct().Count();

        Week = DateServices.GetCurrentWeek(DateTime.UtcNow);
        var event_count = (from u in Context.Events
            where u.date.Date >= Week.Item1.Date && u.date.Date <= Week.Item2.Date && u.admin_approval != false
            select u).Count();
        
        EmployeeCount = emp_count;
        EventCount = event_count;
    }
    
    /// <summary>
    /// Retrieves all events that are scheduled for the current week.
    /// </summary>
    /// <returns>
    /// A list of Event objects, each representing an event that is scheduled for the current week.
    /// </returns>
    /// <remarks>
    /// This method retrieves all events from the database where the event's date is within the current week.
    /// The current week is defined as the period from the date stored in the Week.Item1 property to seven days after that date.
    /// The method returns a list of distinct events, meaning that if an event occurs more than once in the same week, it is only included once in the list.
    /// </remarks>
    public List<CaveroAppContext.Event> GetAllEvents()
    {
        // Context.Events.Select(x => x);
        var Info = (from events in Context.Events
            where events.date.Date >= Week.Item1 && events.date.Date <= Week.Item1.AddDays(7)
            select events).Distinct().ToList();

        return Info;
    }
    
    /// <summary>
    ///    This function gets the number of participants for a given event.
    ///     It returns the count of how many participants that event has.
    /// </summary>
    /// <param name="ev">
    ///     The event to get the participants for.
    /// </param>
    public int GetEventParticipantsCount(CaveroAppContext.Event ev)
    {
        return (from e in Context.Events
            join ea in Context.EventAttendances on e.ID equals ea.event_id
            where e.Equals(ev)
            select ea).Count();
    }
    
    public void OnGet()
    {
        // Remove eventsinitialset if it was created in events, so the information is not stored between pages.
        // This is used so that the event week view starts on the date of today when you navigate back to it.
        HttpContext.Session.Remove("EventsInitialSet");
        HttpContext.Session.Remove("AttendanceInitialSet");
        // Call this function to populate the fields with how many employees are present today,
        // and how many events are happening  this week.
        GetTodayStats();
    }
    
    /// <summary>
    ///     This function checks if the user is already checked in on the given date in string format.
    /// </summary>
    /// <param name="date">
    ///    The date to check if the user is already checked in on. This date is given as string, in the format of dd-mm-yyyy.
    /// </param>
    /// <returns>
    ///     Returns a JsonResult, which is used by AJAX to check if the user is already checked in on the given date.
    /// </returns>
    public JsonResult OnGetCheckDate(string date)
    {
        var dateSplit = date.Split("-").Select(x => Convert.ToInt32(x)).ToArray();
        var parsedDate = DateTime.SpecifyKind(new DateTime(dateSplit[2], dateSplit[1], dateSplit[0]), DateTimeKind.Utc);
        var userID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var exists = Context.Attendances.Any(x => x.date.Date == parsedDate.Date && x.user_id == userID);
        // Invert the result, if exists is true, it means the user is already checked in on that date.
        // If we do not invert, returning true would mean the json is valid, and this would make the check in button submittable.
        return new JsonResult(!exists);
    }
    
    /// <summary>
    /// Checks in a user for a specific date.
    /// </summary>
    /// <remarks>
    /// This method is called when the user submits the form to check in for a specific date.
    /// It retrieves the user's ID from the current user's claims, and then tries to parse the date from the form.
    /// If the date is successfully parsed, it creates a new Attendance object with the user's ID and the parsed date,
    /// adds it to the database, and then saves the changes to the database.
    /// After the check-in process is completed, it redirects the user to the Dashboard page.
    /// </remarks>
    /// <returns>
    /// A RedirectToPageResult that redirects the user to the Dashboard page.
    /// </returns>
    public IActionResult OnPostDateCheckInUser()
    {
        var userID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if(DateTime.TryParseExact(CheckModel.Date, "dd-MM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime parsedDate))
        {
            parsedDate = DateTime.SpecifyKind(parsedDate, DateTimeKind.Utc);
            var att = new CaveroAppContext.Attendance()
            {
                user_id = userID,
                date = parsedDate,
            };
            Context.Add(att);
            Context.SaveChanges();
        }
        return RedirectToPage("/Dashboard");
    }


}

ProjectC/CaveroApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CaveroApp.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

ProjectC/CaveroApp/Pages/adminUserInfo.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using CaveroApp.Areas.Identity.Data;
using CaveroApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CaveroApp.Pages;
[Authorize(Roles = "Admin")]

public class adminUserInfo : PageModel
{
    public CaveroAppContext Context { get; }
    public void OnGet()
    {
        
    }
    public adminUserInfo(CaveroAppContext context)
    {
        Context = context;
    }

    
    /// <summary>
    /// Retrieves all users from the database.
    /// </summary>
    /// <returns>
    /// A list of CaveroAppUser objects, each representing a user in the database.
    /// </returns>
    public List<CaveroAppUser> Users()
    {
        return Context.Users.ToList();
    }
    
    /// <summary>
    /// Updates a user's information in the database.
    /// </summary>
    /// <param name="updatedUser">The user object containing the updated information.</param>
    /// <returns>
    /// A RedirectToPageResult that redirects the user to the current page.
    /// </returns>
    /// <remarks>
    /// This method is called when the admin submits the form to update a user's information.
    /// It retrieves the user from the database using the ID from the updatedUser parameter,
    /// updates the user's properties with the new values from the updatedUser object,
    /// and then saves the changes to the database.
    /// The user's email is also used to update the UserName, NormalizedEmail, and NormalizedUserName properties.
    /// </remarks>
    public IActionResult OnPostUpdateUser(CaveroAppUser updatedUser)
    {
        var userToChange = Context.Users.First(x => x.Id == updatedUser.Id);
        userToChange.FirstName = updatedUser.FirstName;
        userToChange.LastName = updatedUser.LastName;
        userToChange.Email = updatedUser.Email;
        userToChange.UserName = updatedUser.Email;
        userToChange.NormalizedEmail = updatedUser.Email.ToUpper();
        userToChange.NormalizedUserName = updatedUser.Email.ToUpper();
        Context.SaveChanges();
        return RedirectToPage();
    }
    
    /// <summary>
    /// Deletes a user from the database.
    /// </summary>
    /// <param name="userToDelete">The user to be deleted.</param>
    /// <returns>
    /// A RedirectToPageResult that redirects the user to the current page.
    /// </returns>
    /// <remarks>
    /// This method is called when the admin submits the form to delete a user.
    /// It retrieves the user from the database using the ID from the userToDelete parameter,
    /// removes the user from the database, and then saves the changes to the database.
    /// </remarks>
    public IActionResult OnPostDeleteUser(CaveroAppUser userToDelete)
    {
        
        var user = Context.Users.First(x => x.Id == userToDelete.Id);
        Context.Remove(user);
        Context.SaveChanges();
        return RedirectToPage();
    }

}

ProjectC/CaveroApp/Pages/Aanwezig_button.cshtml
@page
@model CaveroApp.Pages.Aanwezig_button

<!DOCTYPE html>

<html>
<head>
    <title></title>
    <link rel="stylesheet" href="css/Button.css" />
</head>
<body>
<div>
    @if (@Model.AvailableToday())
    {
        <p class="message-aanwezig">U bent aanwezig op het kantoor vandaag</p>
        <form class="form-button" method="post" asp-page="Aanwezig_button" asp-page-handler="SetUnavailable">
            <button id="submitButton" class="button afwezig">Zet uzelf afwezig</button>
        </form>
    }
    else
    {
        <p class="message-afwezig">U bent afwezig op het kantoor vandaag</p>
        <form class="form-button" method="post" asp-page="Aanwezig_button" asp-page-handler="SetAvailable">
            <button id="submitButton" class="button aanwezig">Zet uzelf aanwezig</button>
        </form> 
    }
</div>
</body>
</html>

ProjectC/CaveroApp/Pages/Attendance.cshtml
@page
@using System.Globalization
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject CaveroAppContext Context
@model CaveroApp.Pages.Attendance

@{
    ViewData["Title"] = "Aanwezige";
    Layout = "Shared/CaveroLayoutResponsive";
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="preload" as="style" href="css/eventheader.css">
    <link rel="stylesheet" href="css/eventheader.css"/>
    <link rel="stylesheet" href="css/events.css"/>
    <link rel="stylesheet" href="css/layout.css"/>
    <link rel="stylesheet" href="css/attendance.css"/>
    var userID = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
}

@section HeaderContent
{
    <div class="wrapper">
        <form method="post" asp-page="Attendance" asp-page-handler="WeekBackward">
            <button class="header-text tooltip" style="font-size: 30px;" type="submit">
                <p><</p>
                <div class="bottom">
                    <p>Vorige week</p>
                    <i></i>
                </div>
            </button>
        </form>
        <form method="post" asp-page="Attendance" asp-page-handler="WeekForward">
            <button class="header-text tooltip" style="font-size: 30px;" type="submit">
                <p>></p>
                <div class="bottom">
                    <p>Volgende week</p>
                    <i></i>
                </div>
            </button>
        </form>
        <h1 class="header-text" style="text-shadow: 2px 2px 2px var(--collection-1-cavero-blackish-grey);">
            @($"{@Model.Week.Item1.ToString("dd-MM-yyyy", CultureInfo.InvariantCulture)} - " +
              $"{@Model.Week.Item2.ToString("dd-MM-yyyy", CultureInfo.InvariantCulture)}")
        </h1>
    </div>
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
    <style>
    </style>
</head>
<body>
<div class="main">
    <div class="week-container">
        @foreach (var evArr in @Model.GetWeekAttendances())
        {
            <div class="day-wrapper">
                <div class="day">
                    <h1>@evArr.Date.ToString("ddd")</h1>
                    @if (@evArr.Date.Date.Equals(DateTime.UtcNow.Date))
                    {
                        <h2 style="color: var(--collection-1-cavero-paars); text-shadow: 1px 1px 1px grey;">@evArr.Date.Day</h2>
                    }
                    else
                    {
                        <h2>@evArr.Date.Day</h2>
                    }
                </div>

                <div class="item @(evArr.Date.ToString("ddd", CultureInfo.InvariantCulture))" id="@(evArr.Date.ToString("dddd", CultureInfo.InvariantCulture))">
                    <input type="text" id="mySearchInput-@evArr.Date.Date" Date="@evArr.Date.Date" placeholder="Zoek naar namen.." title="Type in a name">
                    @if (!@Model.IsAttending(userID, evArr.Date))
                    {
                        <form class="form-button" method="post" asp-page="Attendance" asp-page-handler="UserJoin" asp-route-userID="@userID"
                              asp-route-date="@evArr.Date.Date.ToString("dd-MM-yyyy")">
                            <button class="button sign-up" style="flex: 1; justify-content: center;" type="submit">
                                <p>AANWEZIG ZETTEN</p>
                            </button>
                        </form>
                    }
                    else
                    {
                        <form class="form-button" method="post" asp-page="Attendance" asp-page-handler="UserLeave" asp-route-userID="@userID"
                              asp-route-date="@evArr.Date.Date.ToString("dd-MM-yyyy")">
                            <button class="button sign-out" style="flex: 1; justify-content: center;" type="submit">
                                <p>AFWEZIG ZETTEN</p>
                            </button>
                        </form>
                    }
                    @foreach (var us in evArr.allUsers.OrderBy(x => x.FirstName))
                    {
                        <div class="attendance-card attendance-@evArr.Date.Date">
                            @if (!System.IO.File.Exists(@$"wwwroot/img/profilepictures/avatar{@us.Id}.png"))
                            {
                                var user = Context.Users.First(x => x.Id == @us.Id);
                                ProfilePictureGenerator.MakePF(user.FirstName, user.LastName, @us.Id!);
                            }
                            <img src="img/profilepictures/avatar@(us.Id).png"/>
                            <h1>@us.FirstName @us.LastName</h1>
                            <span class="attendance-user-info" data-attendance-id="@us.Id">
                                <ion-icon name="information-circle-outline"></ion-icon>
                            </span>
                            
                        </div>
                        
                        <!-- Modal Content -->
                        <!-- Has to be loaded here so it gets filled up with the unique information for each card. -->
                        <div class="event-modal modal-card-@us.Id">
                            <div class="event-modal-content">
                                <div class="event-modal-header">
                                    <img src="img/profilepictures/avatar@(@us.Id).png"/>
                                    <h1 style="justify-content: flex-start; padding: 10px;">@us.FirstName @us.LastName</h1>
                                    <span class="close close-@us.Id" style="justify-content: flex-start">&times;</span>
                                </div>
                                <div class="line"></div>
                                <div class="event-modal-row">
                                    <h1>@us.Email</h1>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
</div>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>

<script>
var infoSpans = document.querySelectorAll(".attendance-user-info");

infoSpans.forEach(function (spans) {
    spans.addEventListener("click", function () {
        // Find the corresponding modal based on data attribute or class.
        var cardId = spans.getAttribute("data-attendance-id");
        var modal = document.querySelector(".modal-card-" + cardId);
        var span = document.getElementsByClassName("close-" + cardId)[0];
        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
            modal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }

        // Open the modal.
        modal.style.display = "flex";
    });
});

var allSearchInputs = document.querySelectorAll("input[id^='mySearchInput-']");
allSearchInputs.forEach(function (inputs) {
    inputs.addEventListener("keyup", function () {
          var date = inputs.getAttribute("Date");
          var filter = inputs.value.toUpperCase();
          var allUsers = document.getElementsByClassName("attendance-" + date);
        
          // Loop through all list items, and hide those who don't match the search query
          for (i = 0; i < allUsers.length; i++) {
            var h1 = allUsers[i].getElementsByTagName("h1")[0];
            var txtValue = h1.textContent || h1.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
              allUsers[i].style.display = "";
            } else {
              allUsers[i].style.display = "none";
            }
          }
    });
});

</script>
</html>

ProjectC/CaveroApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectC/CaveroApp/Pages/adminUserInfo.cshtml
@page
@using System.Security.Claims
@using CaveroApp.Areas.Identity.Data
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model CaveroApp.Pages.adminUserInfo
@inject SignInManager<CaveroAppUser> SignInManager
@inject CaveroAppContext Context

@{
    Layout = "Shared/CaveroLayoutResponsive";
}


@section HeaderContent
{
    <h1 style="color: white; font-size: 24px; font-weight:  600; font-family: 'Montserrat', sans-serif;">Kies hier een gebruiker om hun informatie aan te passen.</h1>
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="css/events.css"/>
    <link rel="stylesheet" href="css/layout.css"/>
    <link rel="stylesheet" href="css/eventheader.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <title></title>
    <style>
        .custom-event-card {
            max-width: 460px;
            position: relative;
        }
        .custom-button-container {
            display: inline flex;
            justify-content: center;
        }
        .custom-button-small {
            max-width: 65px;
            margin-right: 5px;
        }
        .user-edit-list{
            display: flex;
            align-items: center;
            max-height: 88vh;
            width: fit-content;
            flex-direction: column;
            margin-top: 15px;
            overflow-y: auto;
            overflow-x: hidden;
            padding: 10px;
            border: 2px solid darkgray;
            border-radius: 15px;
            text-align: center;
        }
    </style>
</head>
<body>
<div style="display: flex; justify-content: center; width: 100%; height: 100%;">
   <div class="user-edit-list">
       @foreach (var user in @Model.Users())
       {
           <div class="event-card custom-event-card">
               <p>First Name: @(user.FirstName)</p>
               <p>Last Name: @(user.LastName)</p>
               <p>Email: @(user.Email)</p>
               <div class="custom-button-container">
                   <button class="button edit custom-button-small" data-user-id="@user.Id" data-firstName="@user.FirstName" data-lastName="@user.LastName" data-email="@user.Email">Edit</button>
                   <form method="post" asp-page-handler="DeleteUser" onsubmit="return confirm('Are you sure you want to delete this user?');">
                       <input type="hidden" name="userToDelete.Id" value="@user.Id"/>
                       <button class="button delete custom-button-small" type="submit">Delete</button>
                   </form>
               </div>
           </div>
       }
   </div>
   <div id="editModal" class="modal">
       <div class="modal-content">
           <span class="close" onclick="closeModal()">&times;</span>
           <form method="post" asp-page-handler="UpdateUser">
               @*Disabled id for now, because of potential confusion*@
               @* <label for="editId">ID:</label> *@
               <input type="text" id="editId" name="Id" style="display: none;" readonly>
   
               <label for="editFirstName">First Name:</label>
               <input type="text" id="editFirstName" name="FirstName">
   
               <label for="editLastName">Last Name:</label>
               <input type="text" id="editLastName" name="LastName">
   
               <label for="editEmail">Email:</label>
               <input type="text" id="editEmail" name="Email">
   
               <input type="submit" value="Update">
           </form>
       </div>
   </div> 
</div>


<script>
        
        function openModal(userId, firstName, lastName, email) {
            document.getElementById("editId").value = userId;
            document.getElementById("editFirstName").value = firstName;
            document.getElementById("editLastName").value = lastName;
            document.getElementById("editEmail").value = email;
            document.getElementById("editModal").style.display = "block";
        }
        function closeModal() {
            document.getElementById("editModal").style.display = "none";
        }
        var editButtons = document.getElementsByClassName("button edit custom-button-small");
        for (var i = 0; i < editButtons.length; i++) {
            editButtons[i].addEventListener("click", function () {
                var userId = this.getAttribute("data-user-id");
                var firstName = this.getAttribute("data-firstName");
                var lastName = this.getAttribute("data-lastName");
                var email = this.getAttribute("data-email");

                openModal(userId, firstName, lastName, email);
            });
        }
    </script>
</body>
</html>